"""paper.state not null

Revision ID: 620d08f7e918
Revises: 764d45b06048
Create Date: 2025-01-11 23:06:47.383517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620d08f7e918'
down_revision: Union[str, None] = '764d45b06048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'state',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'state',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
