"""new fields for paper

Revision ID: e4633e8fc573
Revises: 620d08f7e918
Create Date: 2025-01-14 21:01:46.451624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4633e8fc573'
down_revision: Union[str, None] = '620d08f7e918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('venue', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('journal', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('url', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('is_open_access', sa.Boolean(), nullable=True))
    op.add_column('papers', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'pdf_url')
    op.drop_column('papers', 'is_open_access')
    op.drop_column('papers', 'url')
    op.drop_column('papers', 'journal')
    op.drop_column('papers', 'venue')
    # ### end Alembic commands ###
