"""init

Revision ID: 764d45b06048
Revises: 
Create Date: 2025-01-11 23:05:34.584094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d45b06048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('support_level', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('search_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_citations',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('citation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'citation_id')
    )
    op.create_table('paper_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_query_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('search_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['search_log_id'], ['search_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_references',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'reference_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_references')
    op.drop_table('paper_query_sources')
    op.drop_table('paper_concepts')
    op.drop_table('paper_citations')
    op.drop_table('search_logs')
    op.drop_table('papers')
    op.drop_table('paper_evaluations')
    # ### end Alembic commands ###
